### ISSUE TITLE
More hardware results

### ISSUE THREAD

**Issue by ISSOtm** [kkzero241/gdma-guy#3]
I am testing this on my 001 and Player, and also checking if my other models match your observations.

![IMG_20220122_202223.jpg](https://user-images.githubusercontent.com/15271137/150652759-813fb5a2-9126-47fe-a916-a8a86cbbdb96.jpg)

This one features the red bar as well, though it does flicker.

**Comment by kkzero241** [comment]
Thanks! So that pretty much confirms the SP in general doesn't glitch the transferred GFX. And I did notice the red bar flicker, too.

**Comment by ISSOtm** [comment]
Here is a screenshot of my Player, taken via GBI-HF (and recorded via a capture card)

![mpv-shot0001](https://user-images.githubusercontent.com/15271137/150653228-6d53e11f-cfdf-4358-9d26-d1de5d4d691d.jpg)

**Comment by kkzero241** [comment]
Ah, interesting, he gets kinda raspy.
Thanks again, those are the two hardware units I don't have any of, this helps quite a bit!

**Comment by ISSOtm** [comment]
I also confirm the (apparent) same glitching on my CGB-B, CGB-C, and CGB-D.

**Comment by ISSOtm** [comment]
Well, fortunately, since the result seems identical everywhere, I can just make a recording of it on my Player!

https://user-images.githubusercontent.com/15271137/150653927-9e07c158-6fdd-434d-af45-d05e1f432d0c.mp4

(Do feel free to use those in your README :)

**Comment by kkzero241** [comment]
Excellent, it can be concluded that this is an SP vs. non-SP thing.
